version: '3'
services:
  web:
    build:
      ./
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules

networks:
  app-network:
    driver: bridge