version: '3'
services:
  web:
    build:
      ./
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge